### ISSUE TITLE
Feature Request - Upgrade for 0.8.X foundry

### ISSUE THREAD

**Issue by p4535992** [mtvjr/background-volume#8]
I've always liked this module. Is there an update for 0.8.3 planned in the future?

**Comment by mtvjr** [comment]
Hi p4535992,

I've attempted to update BV to 0.8.X several times, but unfortunately, each core release has bugs preventing support right now. I hope they are fixed in 0.8.6. If not, I'll work around the issue. As the workaround could break compatibility with other mods, I'm avoiding that path at the moment.

In the meantime, I've created a development branch focused on 0.8.X compatibility. This has almost everything working in 0.8.5 except for the global "Ambient Volume" slider, which is broken in the core. If you want to try it out, you can use this manifest https://raw.githubusercontent.com/mtvjr/background-volume/0.8.x/module.json

Hope this helps,
Michael
